In [31]:
import seaborn as sns
import pandas as pd
import statistics as st
import matplotlib.pyplot as plt
# Read the data from uploaded file car details v4.csv
data=pd.read_csv('/content/car details v4.csv')
data

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,Mahindra,XUV500 W8 [2015-2017],850000,2016,90300,Diesel,Manual,Surat,White,First,Individual,2179 cc,138 bhp @ 3750 rpm,330 Nm @ 1600 rpm,FWD,4585.0,1890.0,1785.0,7.0,70.0
2055,Hyundai,Eon D-Lite +,275000,2014,83000,Petrol,Manual,Ahmedabad,White,Second,Individual,814 cc,55 bhp @ 5500 rpm,75 Nm @ 4000 rpm,FWD,3495.0,1550.0,1500.0,5.0,32.0
2056,Ford,Figo Duratec Petrol ZXI 1.2,240000,2013,73000,Petrol,Manual,Thane,Silver,First,Individual,1196 cc,70 bhp @ 6250 rpm,102 Nm @ 4000 rpm,FWD,3795.0,1680.0,1427.0,5.0,45.0
2057,BMW,5-Series 520d Luxury Line [2017-2019],4290000,2018,60474,Diesel,Automatic,Coimbatore,White,First,Individual,1995 cc,188 bhp @ 4000 rpm,400 Nm @ 1750 rpm,RWD,4936.0,1868.0,1479.0,5.0,65.0
2058,Mahindra,Bolero Power Plus ZLX [2016-2019],670000,2017,72000,Diesel,Manual,Guwahati,White,First,Individual,1493 cc,70 bhp @ 3600 rpm,195 Nm @ 1400 rpm,RWD,3995.0,1745.0,1880.0,7.0,NaN

In [32]:
#checking the data duplicates
data.duplicated().sum()

np.int64(0)

In [33]:
#find the count of Make category to decide which type encoding have to apply
data['Make'].value_counts() # Multiple categories are there so we have to apply Target encoding to transfer text data to numerical

Make
Maruti Suzuki    440
Hyundai          349
Mercedes-Benz    171
Honda            158
Toyota           132
Audi             127
BMW              121
Mahindra         119
Tata              57
Volkswagen        50
Ford              48
Renault           43
Skoda             40
Land Rover        33
Kia               23
Jeep              18
MG                17
Jaguar            17
Nissan            16
Volvo             16
Porsche           15
MINI              11
Datsun             8
Chevrolet          7
Lexus              6
Mitsubishi         4
Ssangyong          3
Rolls-Royce        3
Isuzu              2
Fiat               2
Maserati           1
Lamborghini        1
Ferrari            1
Name: count, dtype: int64

In [34]:
#find the count of Model category to decide which type encoding have to apply
data['Model'].value_counts() # Multiple categories are there so we have to do Target encoding

Model
X1 sDrive20d xLine                 15
Swift DZire VDI                    14
Fortuner 2.8 4x2 AT [2016-2020]    13
City V                             13
Swift VXi [2014-2017]              12
                                   ..
Alto 800 Std                        1
Innova 2.0 G1 BS-IV                 1
GLA 200 d Style                     1
Fiesta Titanium Diesel              1
Wagon R LXi 1.0 CNG                 1
Name: count, Length: 1050, dtype: int64

In [35]:
#find the count of Fuel Type category to decide which type encoding have to apply
data['Fuel Type'].value_counts() # Multiple categories are there so we have to do Target encoding

Fuel Type
Diesel          1049
Petrol           942
CNG               50
Electric           7
LPG                5
Hybrid             3
CNG + CNG          1
Petrol + CNG       1
Petrol + LPG       1
Name: count, dtype: int64

In [36]:
#find the count of Transmission category to decide which type encoding have to apply
data['Transmission'].value_counts() # Only two categories are there so we can do onehot encoding

Transmission
Manual       1133
Automatic     926
Name: count, dtype: int64

In [37]:
#find the count of Owner category to decide which type encoding have to apply
data['Owner'].value_counts() # Multiple categories are there so we have to do Target encoding

Owner
First               1619
Second               373
Third                 42
UnRegistered Car      21
Fourth                 3
4 or More              1
Name: count, dtype: int64

In [38]:
#find the count of Seller Type category to decide which type encoding have to apply
data['Seller Type'].value_counts() # Only three categories are there so we can do onehot encoding to transfer text data to numerical

Seller Type
Individual                 1997
Corporate                    57
Commercial Registration       5
Name: count, dtype: int64

In [39]:
#find the count of DriveTrain category to decide which type encoding have to apply
data['Drivetrain'].value_counts() # Only three categories are there so we can do onehot encoding

Drivetrain
FWD    1330
RWD     321
AWD     272
Name: count, dtype: int64

In [40]:
# Apply onehot encoding for minimal categories
data = pd.get_dummies(data, columns=['Transmission'],dtype=int,drop_first=True)
data = pd.get_dummies(data, columns=['Seller Type'],dtype=int,drop_first=True)
data = pd.get_dummies(data, columns=['Drivetrain'],dtype=int,drop_first=True)

In [41]:
#Apply Target encoding since there multiple values in the below feature cloumns
data['Make'] = data['Make'].map(data.groupby('Make')['Price'].mean())
data['Model'] = data['Model'].map(data.groupby('Model')['Price'].mean())
data['Owner'] = data['Owner'].map(data.groupby('Owner')['Price'].mean())
data['Fuel Type'] = data['Fuel Type'].map(data.groupby('Fuel Type')['Price'].mean())

In [42]:
#Apply Target encoding since there multiple values in the below feature cloumns
data['Location'] = data['Location'].map(data.groupby('Location')['Price'].mean())
data['Color'] = data['Color'].map(data.groupby('Color')['Price'].mean())
data['Engine'] = data['Engine'].map(data.groupby('Engine')['Price'].mean())
data['Max Power'] = data['Max Power'].map(data.groupby('Max Power')['Price'].mean())
data['Max Torque'] = data['Max Torque'].map(data.groupby('Max Torque')['Price'].mean())
data

,Make,Model,Price,Year,Kilometer,Fuel Type,Location,Color,Owner,Engine,...,Length,Width,Height,Seating Capacity,Fuel Tank Capacity,Transmission_Manual,Seller Type_Corporate,Seller Type_Individual,Drivetrain_FWD,Drivetrain_RWD
0,6.221076e+05,5.050000e+05,505000,2017,87150,1.322041e+06,1.977764e+06,1.201441e+06,1.714159e+06,4.690732e+05,...,3990.0,1680.0,1505.0,5.0,35.0,1,1,0,1,0
1,5.348000e+05,4.147142e+05,450000,2014,75000,2.101848e+06,1.475745e+06,1.775398e+06,1.438051e+06,6.253688e+05,...,3995.0,1695.0,1555.0,5.0,42.0,1,0,1,1,0
2,7.232635e+05,2.931250e+05,220000,2011,67000,1.322041e+06,9.643333e+05,1.243000e+06,1.714159e+06,5.570389e+05,...,3585.0,1595.0,1550.0,5.0,35.0,1,0,1,1,0
3,1.729545e+06,7.622500e+05,799000,2019,37500,1.322041e+06,7.424000e+05,1.330753e+06,1.714159e+06,5.570389e+05,...,3995.0,1745.0,1510.0,5.0,37.0,1,0,1,1,0
4,1.729545e+06,1.927200e+06,1950000,2018,69000,2.101848e+06,1.721570e+06,1.201441e+06,1.714159e+06,2.196143e+06,...,4735.0,1830.0,1795.0,7.0,55.0,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,1.083479e+06,8.500000e+05,850000,2016,90300,2.101848e+06,2.980400e+06,1.775398e+06,1.714159e+06,1.286356e+06,...,4585.0,1890.0,1785.0,7.0,70.0,1,0,1,1,0
2055,7.232635e+05,2.625000e+05,275000,2014,83000,1.322041e+06,1.507257e+06,1.775398e+06,1.438051e+06,2.611538e+05,...,3495.0,1550.0,1500.0,5.0,32.0,1,0,1,1,0
2056,1.474625e+06,2.400000e+05,240000,2013,73000,1.322041e+06,1.149000e+06,9.630350e+05,1.714159e+06,4.526922e+05,...,3795.0,1680.0,1427.0,5.0,45.0,1,0,1,1,0
2057,3.768967e+06,4.337900e+06,4290000,2018,60474,2.101848e+06,1.385207e+06,1.775398e+06,1.714159e+06,3.010732e+06,...,4936.0,1868.0,1479.0,5.0,65.0,0,0,1,0,1
2058,1.083479e+06,7.283333e+05,670000,2017,72000,2.101848e+06,8.400000e+05,1.775398e+06,1.714159e+06,1.207216e+06,...,3995.0,1745.0,1880.0,7.0,NaN,1,0,1,0,1

In [43]:
# check null value
data.isnull().sum()

Make                        0
Model                       0
Price                       0
Year                        0
Kilometer                   0
Fuel Type                   0
Location                    0
Color                       0
Owner                       0
Engine                     80
Max Power                  80
Max Torque                 80
Length                     64
Width                      64
Height                     64
Seating Capacity           64
Fuel Tank Capacity        113
Transmission_Manual         0
Seller Type_Corporate       0
Seller Type_Individual      0
Drivetrain_FWD              0
Drivetrain_RWD              0
dtype: int64

In [44]:
from sklearn.impute import SimpleImputer
#Define numerical columns and text columns
num_col = data.select_dtypes(include=['number']).columns
cat_col = data.select_dtypes(exclude=["number"]).columns

# Removes null values by median
num_imputer = SimpleImputer(strategy="median")
data[num_col] = num_imputer.fit_transform(data[num_col])
data.isnull().sum()

Make                      0
Model                     0
Price                     0
Year                      0
Kilometer                 0
Fuel Type                 0
Location                  0
Color                     0
Owner                     0
Engine                    0
Max Power                 0
Max Torque                0
Length                    0
Width                     0
Height                    0
Seating Capacity          0
Fuel Tank Capacity        0
Transmission_Manual       0
Seller Type_Corporate     0
Seller Type_Individual    0
Drivetrain_FWD            0
Drivetrain_RWD            0
dtype: int64

In [45]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
#Apply Standard scaling to transform data
scaler = StandardScaler()

data[num_col] = scaler.fit_transform(data[num_col])

In [65]:
X = data.drop("Price", axis=1) #define feature columns
y = data["Price"] #define target column

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

In [47]:
from sklearn.linear_model import LinearRegression #first model supervised regression model

model = LinearRegression()  # model named as model
model.fit(X_train, y_train) # teaching the trained values - machine learning happend

LinearRegression()

In [48]:
y_pred = model.predict(X_test) # predict a targe model using test data
y_test
y_pred # predicted answers

array([ 1.26507666e+00, -3.73106601e-01, -4.18919656e-01, -3.94030458e-01,
       -3.78278775e-01, -5.64748132e-01, -2.69649362e-01,  3.05838206e-01,
       -3.26164865e-01,  9.43706707e-01, -4.88981340e-01, -4.49090708e-01,
       -3.76069542e-01,  3.01795353e+00, -4.57134339e-01, -5.71424201e-01,
       -3.74165615e-01, -4.50659244e-01,  7.49142146e-02, -5.32773379e-01,
        1.55508017e+00, -4.55925316e-01, -4.42980570e-01, -5.36415753e-01,
       -4.85055733e-01,  1.14397764e-01, -2.86995510e-01, -2.27857228e-01,
        7.18894307e-02, -4.51744594e-01, -4.03477493e-01,  1.73959303e+00,
        1.12981620e+00, -4.31574622e-01, -5.84949067e-01, -3.69309345e-01,
       -5.62178661e-01,  2.15915607e+00, -5.48160649e-01, -2.01312140e-01,
       -3.97279014e-01, -5.60746909e-01,  1.01413838e+00, -5.75615576e-01,
       -4.82878225e-01,  3.01100292e+00,  3.13748907e-01, -5.64427217e-01,
       -4.86307213e-01,  9.07584184e-01, -1.08465354e-01,  2.13184153e+00,
       -5.14581747e-01, -5.44180132e-01, -5.44376177e-01,  8.65327238e-02,
       -4.57217665e-01, -6.98609690e-01, -9.58062350e-02,  2.47747856e-01,
       -1.93067239e-01, -5.68576073e-01, -6.08381811e-01, -5.42938432e-01,
       -1.61515384e-01, -4.44028105e-01, -3.85747677e-01, -6.16495279e-01,
       -4.74770168e-01,  9.00544832e-02,  2.83750590e-01, -4.51807801e-01,
       -1.06780543e-01, -4.76345084e-01,  3.11677676e-01,  4.69987102e+00,
       -4.02744741e-01, -5.61673140e-01, -6.37369563e-01,  1.21751229e+00,
       -2.44922324e-01, -5.41010794e-01, -5.84069256e-01, -5.27545711e-01,
       -1.41703458e-01, -5.31543635e-01, -5.35151915e-01, -2.09667710e-01,
       -5.24644936e-01, -4.63124644e-01, -3.97274265e-01, -5.33314261e-01,
       -2.38817767e-01,  1.10826168e-01, -6.39463247e-01, -6.16444336e-01,
       -6.37399851e-01, -5.16639634e-01, -4.93211412e-01, -5.86209416e-01,
       -3.59314841e-01, -1.32501098e-01,  2.05846265e-01,  3.07215259e-01,
       -5.95805460e-01, -5.29192792e-01,  5.44610611e+00, -4.71004726e-01,
        3.95479786e-01, -5.79733299e-01,  1.87482973e-01,  7.69800936e-04,
        1.36664889e+00, -5.00604977e-01, -5.94127189e-01,  2.14669298e+00,
       -4.80140430e-01, -6.70987947e-01,  6.96817713e-01, -4.35551893e-01,
        1.37718185e-01, -2.33153686e-01, -5.74288366e-02, -7.20174218e-01,
       -5.68488862e-01, -5.65819677e-02, -6.61010537e-01, -4.33970480e-01,
       -5.04572552e-01, -5.03657384e-01, -5.00127212e-01, -2.98780269e-01,
       -3.63563392e-01, -3.70909037e-01, -8.71912230e-02,  3.20191863e-01,
       -2.99140861e-01,  2.92629804e-01,  1.54521675e+00,  1.08135591e+00,
        1.08607104e-01,  1.16331072e+00, -4.69287133e-01, -9.56765031e-02,
        1.11145347e+00, -3.74238806e-01,  1.13037156e+00, -3.74375887e-01,
       -5.77122077e-01, -4.20872478e-01, -6.24825258e-01, -5.80038276e-01,
       -3.49685397e-01,  4.53715171e-01,  1.56481562e-01, -5.20052615e-01,
        1.09242887e+00, -3.84399294e-01,  1.13453359e+00, -5.13055087e-01,
        1.85843393e+00, -5.70499618e-01, -5.98379023e-01, -2.57131116e-01,
       -5.03647205e-01, -5.01042189e-01, -5.78772793e-01,  3.40957132e-01,
        4.79957724e-01, -4.42872438e-01,  1.10613227e+00, -5.19075361e-01,
       -4.25868687e-01, -4.42472766e-01,  3.20369016e+00, -4.45873092e-01,
        7.99753707e-01, -4.01708142e-01, -6.04859920e-01, -2.95388172e-01,
        1.39352324e+00, -4.95300940e-01,  7.19394853e-01, -5.31659611e-01,
       -3.63793212e-01, -4.08665341e-01, -4.95196717e-01, -3.52654438e-01,
        3.81059918e-01,  1.11300201e+00,  9.68565067e-02,  3.05920844e-01,
        9.71241516e-01, -3.58399994e-01, -2.86211910e-01,  1.91542757e-01,
        1.85560942e+00,  1.45248594e-01, -2.20012462e-01, -2.74608579e-01,
       -5.21042618e-01, -4.76050030e-01, -5.54942999e-01, -5.56380813e-01,
       -4.98399808e-01, -5.13078674e-01, -6.64758418e-01, -5.94419946e-01,
        1.19678686e-03, -3.41571903e-01, -3.84942171e-01, -2.38337023e-02,
        4.60808870e-02, -4.92865223e-01,  1.60470080e+00, -5.53754535e-01,
        1.24383134e+00,  6.28663592e-02, -3.69422378e-02, -2.45787771e-01,
        6.61356645e-01, -7.32913595e-02, -2.89427277e-01,  1.06494841e-01,
       -5.85405792e-01, -5.80929726e-01,  1.80994042e+00, -2.44138167e-01,
       -5.76030374e-01,  3.14687174e-02,  2.06109645e+00, -6.48104901e-01,
       -3.30709525e-01, -5.18297853e-01, -4.95970131e-01, -5.25585987e-01,
       -6.25912892e-01, -4.32148453e-02,  7.20179185e-01, -4.31494223e-01,
       -3.06950387e-01, -5.54206556e-01, -2.28977159e-01, -2.09030952e-01,
       -5.15340012e-01, -2.70507791e-01, -8.19791382e-02,  1.52366883e+00,
        5.27491325e-01, -2.17572003e-01,  1.92957320e-01, -3.98671393e-01,
        1.33390930e+00, -4.84454553e-01, -2.55470004e-01,  2.18156304e-01,
        8.97744561e-03, -4.34383208e-02,  5.35957102e-01, -1.41681522e-01,
        3.31973629e+00, -4.02119450e-01,  1.05594561e+00,  5.40824607e-02,
       -3.20638637e-01,  2.19235145e+00,  1.07953474e-01, -1.08154995e-01,
       -4.01020130e-01, -4.08465125e-01, -4.83048499e-01, -5.48166032e-01,
        1.01521552e+00,  2.11190108e+00,  5.17152194e-01, -2.31627628e-01,
        1.33887042e+00,  1.24360296e+00, -4.57045452e-01,  3.49028392e+00,
        5.47056871e-01, -5.65432211e-01, -3.85514619e-01, -1.06787991e-01,
        1.55357245e+00,  3.45654572e-01,  4.77759229e-01, -3.56592101e-01,
       -2.77059331e-01, -2.57046934e-01, -5.94444024e-01,  3.99574194e-02,
        2.62724340e-01,  1.62117786e-01, -4.86129109e-01, -4.74965708e-01,
       -2.97778012e-01, -4.28202152e-01,  3.71671299e-01,  5.55001456e-02,
       -3.33285298e-01, -5.89980955e-01, -4.03749788e-01, -6.20719511e-01,
       -5.42806249e-01, -4.15910561e-01, -3.15757476e-02, -5.82778667e-01,
       -5.48525177e-01,  2.79263659e+00,  1.22434111e+00,  2.70263914e-02,
       -2.15429330e-01, -4.86931025e-01,  1.12098968e+00, -4.14167081e-01,
       -4.52316366e-01, -5.07943292e-01, -5.60036250e-01, -6.64914228e-01,
       -2.97477440e-01, -4.56148053e-01, -3.04502237e-01,  5.62212783e-02,
       -2.12371677e-01, -1.01691460e-01, -4.35381640e-01, -4.52911149e-01,
       -5.87550120e-01,  5.31345638e-02, -3.85446896e-01, -4.72679860e-01,
       -6.27320251e-01, -5.58387920e-01,  2.13808907e+00, -5.46047061e-01,
       -6.10756688e-01, -5.95234137e-01, -1.63482524e-01, -5.45245177e-01,
        1.09111210e+00, -1.97354278e-01, -5.47683862e-01, -2.48177853e-01,
       -6.10231049e-01, -4.84358982e-01, -3.84298041e-01, -3.79716614e-01,
       -3.35482739e-01, -4.19960344e-01, -6.14293079e-01, -4.47633944e-01,
       -3.68981501e-01,  9.57798487e-01, -4.71206517e-01, -4.29843414e-01,
       -4.82889486e-01, -3.87839032e-01, -3.87843837e-01, -5.79170527e-01,
       -2.71534217e-01,  1.15985283e-01, -4.71065043e-01, -3.33931880e-01,
       -5.04793857e-01,  3.83258733e-01, -4.57923801e-01,  1.80118498e-01,
       -1.24538021e-01,  5.83431999e-01, -3.00044243e-01, -4.90913640e-01,
       -5.12018726e-01, -4.24234830e-01,  1.81321508e+00,  9.51527196e-01,
       -5.89009265e-01,  4.57634265e-01,  2.07701753e-02, -6.15127673e-01,
        4.59232981e-01,  9.12892651e-02, -1.55367990e-02, -5.27487668e-01,
       -5.75424801e-01, -4.37139016e-01,  1.01956163e+00,  9.41335281e-01,
       -1.80416913e-01, -6.97402009e-01, -3.69964546e-01,  3.83396831e-01,
       -2.64141239e-02, -5.77284091e-01, -4.48052021e-01, -3.87953485e-01,
       -5.53725118e-01,  9.70489785e-02, -4.50639692e-01, -5.04037134e-01,
       -3.07070783e-01, -2.68630899e-01, -4.43475928e-01, -2.41497990e-01,
       -4.41210581e-01,  1.36998727e+01, -4.39686203e-02, -5.97619235e-01,
        3.40876607e-01,  1.79567121e+00, -5.64748132e-01, -3.24980227e-01,
       -3.52349544e-01,  6.75579246e-01, -3.82792969e-01,  4.55264504e+00,
        6.14731148e-01, -4.15740769e-01, -4.67890380e-01,  2.06489222e+00,
        7.86561746e+00, -3.16548347e-01, -2.65050722e-01, -3.67229301e-01,
       -3.15283761e-01, -3.74719278e-01, -4.13657212e-01,  1.30548333e-02,
        1.72807652e+00, -4.95748629e-01,  1.29749667e+00, -3.48425764e-01,
        2.27719445e+00, -3.40230181e-01, -4.43484252e-01,  7.90158905e-01,
        2.90418275e-01, -6.18972710e-01, -4.38823860e-01, -2.43307808e-01,
       -3.82319402e-01,  1.32523932e+00,  3.81149637e-01, -2.23140709e-01,
       -5.31558804e-01, -4.53867136e-01, -5.15556823e-01, -4.67640237e-01,
       -4.20670197e-01, -6.21825282e-01, -6.66979258e-01, -4.16458515e-01,
       -4.63968458e-01,  6.76008163e-01,  9.17269907e-01,  1.58212219e-01,
       -3.72899414e-01, -3.32364267e-01,  1.49386869e+00,  6.05431196e-01,
        8.67514942e-02, -3.32917701e-01, -8.75731961e-02,  4.45604547e+00,
       -3.39681124e-01, -5.63843587e-01, -2.42782098e-01,  6.87867849e-01,
       -5.80497552e-01,  1.20862841e+00, -3.58752930e-01,  3.64295039e-01,
       -5.41655113e-01, -5.01878843e-01,  6.84584686e-01, -5.64964753e-01,
       -3.55920545e-01,  1.53036903e+00,  9.42672545e-01,  9.17046644e-01,
       -1.72796931e-01, -4.19975920e-01,  2.11649697e-01, -4.98287277e-01,
       -5.69686586e-01,  5.87353003e-01, -6.40314914e-01, -1.67445262e-02,
        4.58157651e-01, -1.53135796e-01, -3.51836093e-01, -4.45300811e-01,
       -3.61201228e-01, -5.67088289e-01,  5.41331876e-01,  5.52100806e-01,
        1.77079063e-01, -9.62328108e-02, -4.29969895e-02, -3.24992968e-01,
        1.51936621e+00, -5.71965874e-01,  2.14175195e-01, -6.31035830e-01,
       -5.71958477e-01, -4.70124439e-01, -3.65255577e-01,  1.46329303e+00,
       -5.52162912e-01,  1.69375821e-01, -3.58889199e-01, -5.41160364e-01,
       -3.94724477e-01, -5.49093743e-01, -6.14301875e-01])

In [49]:
results = pd.DataFrame({
    "Actual (₹)": y_test.values,
    "Predicted (₹)": y_pred.astype(int),
    "diff": (y_test.values - y_pred).astype(int)

})
results # define actual and predict price

     Actual (₹)  Predicted (₹)  diff
0      1.280130              1     0
1     -0.362913              0     0
2     -0.416647              0     0
3     -0.311245              0     0
4     -0.364980              0     0
..          ...            ...   ...
510   -0.373246              0     0
511   -0.548917              0     0
512   -0.393913              0     0
513   -0.511716              0     0
514   -0.600585              0     0

[515 rows x 3 columns]

In [50]:
from sklearn.metrics import r2_score, mean_absolute_error # regression score and mean absolute error
# Regression metrics 99.63% accuracy
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print(f"\nR² Score: {r2:.4f}")
print(f"Mean Absolute Error: ₹{int(mae):,}")

R² Score: 0.9750
Mean Absolute Error: ₹0

In [51]:
# define train data sample, test data sample, target data sample, target test sample
X.train = model.predict
X.test = model.predict(X_test)
y.train = model.predict(X_train)
y.test = model.predict(X_test)

/tmp/ipython-input-427611164.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  X.test = model.predict(X_test)

In [52]:
from sklearn.model_selection import train_test_split
#train test data to predict
X_train, Xtest, y_train, ytest = train_test_split(X,y,random_state=42)

In [53]:
#train data and test data
X_train.shape

(1544, 21)

In [54]:
# train target, test target
y_train.shape

(1544,)

In [69]:
# Prediting the new selling Price of used car
#--------------------------------------------
new_price = pd.DataFrame({
    "Make": [6.22],
    "Model": [5.05],
    "Year": [2011],
    "Kilometer": [75000],
    "Fuel Type": [2.1],
     "Location": [1.97],
    "Color": [1.20],
    "Owner": [1.71],
    "Engine": [14.6],
    "Max Power": [1],
    "Max Torque": [1],
    "Length": [1],
    "Width": [1],
    "Height": [0],
    "Seating Capacity": [1],
    "Fuel Tank Capacity": [35],
    "Transmission_Manual": [1],
    "Seller Type_Corporate": [1],
    "Seller Type_Individual": [0],
    "Drivetrain_FWD": [1],
    "Drivetrain_RWD": [0]
})

# Scale numerical features
new_price[num_col] = scaler.transform(new_price[num_col])
pred_price = model.predict(new_price)
print(f"Predicted Selling Price of a used Car: ₹{int(pred_price[0]):,}")

KeyError: "['Price'] not in index"