In [1]:
# Supervisory Learning - Logistic Regression
import seaborn as sns
import pandas as pd
import statistics as st
import matplotlib.pyplot as plt

# Read the training data from the uploaded file
data_train=pd.read_csv('/content/train_LZdllcl.csv')
data_train

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,65438,Sales & Marketing,region_7,Master's & above,f,sourcing,1,35,5.0,8,1,0,49,0
1,65141,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,0,60,0
2,7513,Sales & Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,0,50,0
3,2542,Sales & Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,0,50,0
4,48945,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,0,73,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54803,3030,Technology,region_14,Bachelor's,m,sourcing,1,48,3.0,17,0,0,78,0
54804,74592,Operations,region_27,Master's & above,f,other,1,37,2.0,6,0,0,56,0
54805,13918,Analytics,region_1,Bachelor's,m,other,1,27,5.0,3,1,0,79,0
54806,13614,Sales & Marketing,region_9,NaN,m,sourcing,1,29,1.0,2,0,0,45,0
54807,51526,HR,region_22,Bachelor's,m,other,1,27,1.0,5,0,0,49,0

In [16]:
# Read the test data from the uploaded file
data_test=pd.read_csv('/content/test_2umaH9m.csv')
data_test

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score
0,8724,Technology,region_26,Bachelor's,m,sourcing,1,24,NaN,1,1,0,77
1,74430,HR,region_4,Bachelor's,f,other,1,31,3.0,5,0,0,51
2,72255,Sales & Marketing,region_13,Bachelor's,m,other,1,31,1.0,4,0,0,47
3,38562,Procurement,region_2,Bachelor's,f,other,3,31,2.0,9,0,0,65
4,64486,Finance,region_29,Bachelor's,m,sourcing,1,30,4.0,7,0,0,61
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23485,53478,Legal,region_2,Below Secondary,m,sourcing,1,24,3.0,1,0,0,61
23486,25600,Technology,region_25,Bachelor's,m,sourcing,1,31,3.0,7,0,0,74
23487,45409,HR,region_16,Bachelor's,f,sourcing,1,26,4.0,4,0,0,50
23488,1186,Procurement,region_31,Bachelor's,m,sourcing,3,27,NaN,1,0,0,70
23489,5973,Technology,region_17,Master's & above,m,other,3,40,5.0,5,1,0,89

In [3]:
#checking the data duplicates in train data
data_train.duplicated().sum()

np.int64(0)

In [4]:
#checking the data duplicates in test data
data_test.duplicated().sum()

np.int64(0)

In [5]:
# check null values in train data
data_train.isnull().sum()

employee_id                0
department                 0
region                     0
education               2409
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
is_promoted                0
dtype: int64

In [8]:
# Replace the education column null values by mode
data_train.loc[data_train["education"].isna(),"education"] = st.mode(data_train["education"])
data_train.isnull().sum()

employee_id                0
department                 0
region                     0
education                  0
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
is_promoted                0
dtype: int64

In [12]:
# Replace the previous_year_rating column null values by first value
data_train.loc[data_train["previous_year_rating"].isna(),"previous_year_rating"] = data_train["previous_year_rating"][0]
data_train.isnull().sum()

employee_id             0
department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
is_promoted             0
dtype: int64

In [18]:
# Replace the education column null values by mode
data_test.loc[data_test["education"].isna(),"education"] = st.mode(data_test["education"])
data_test.isnull().sum()

employee_id             0
department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
dtype: int64

In [19]:
# Replace the previous_year_rating column null values by first value
data_test.loc[data_test["previous_year_rating"].isna(),"previous_year_rating"] = data_test["previous_year_rating"][1]
data_test.isnull().sum()

employee_id             0
department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
dtype: int64

In [20]:
#Define numerical columns and text columns in the train data
from sklearn.impute import SimpleImputer
num_col_train = data_train.select_dtypes(include=['number']).columns
cat_col_train = data_train.select_dtypes(exclude=["number"]).columns

In [21]:
cat_col_train

Index(['department', 'region', 'education', 'gender', 'recruitment_channel'], dtype='object')

In [22]:
#Define numerical columns and text columns in the test data
from sklearn.impute import SimpleImputer
num_col_test = data_test.select_dtypes(include=['number']).columns
cat_col_test = data_test.select_dtypes(exclude=["number"]).columns

In [23]:
cat_col_test

Index(['department', 'region', 'education', 'gender', 'recruitment_channel'], dtype='object')

In [32]:
num_col_train

Index(['employee_id', 'no_of_trainings', 'age', 'previous_year_rating',
       'length_of_service', 'KPIs_met >80%', 'awards_won?',
       'avg_training_score', 'is_promoted'],
      dtype='object')

In [33]:
num_col_test

Index(['employee_id', 'no_of_trainings', 'age', 'previous_year_rating',
       'length_of_service', 'KPIs_met >80%', 'awards_won?',
       'avg_training_score'],
      dtype='object')

In [28]:
#data_train['department'].value_counts()
#data_train['region'].value_counts()
#data_train['education'].value_counts()
#data_train['gender'].value_counts()
data_train['recruitment_channel'].value_counts()

recruitment_channel
other       30446
sourcing    23220
referred     1142
Name: count, dtype: int64

In [63]:
data_train

,employee_id,department,region,education,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted,gender_m
0,1.161858,0.072031,0.106546,0.098559,0.085013,-0.415276,0.025598,1.198336,0.500460,1.356878,-0.154018,-1.075931,-0.305122,0
1,1.148709,0.090148,0.114188,0.080096,0.083952,-0.415276,-0.627135,1.198336,-0.437395,-0.736986,-0.154018,-0.253282,-0.305122,1
2,-1.402741,0.072031,0.060641,0.080096,0.085013,-0.415276,-0.104948,-0.352878,0.265996,-0.736986,-0.154018,-1.001145,-0.305122,1
3,-1.622829,0.072031,0.116596,0.080096,0.083952,1.226063,0.547785,-1.904092,0.969387,-0.736986,-0.154018,-1.001145,-0.305122,1
4,0.431639,0.107593,0.063274,0.080096,0.083952,-0.415276,1.331064,-0.352878,-0.906322,-0.736986,-0.154018,0.718939,-0.305122,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54803,-1.601223,0.107593,0.074970,0.080096,0.085013,-0.415276,1.722704,-0.352878,2.610632,-0.736986,-0.154018,1.092871,-0.305122,1
54804,1.567147,0.090148,0.078963,0.098559,0.083952,-0.415276,0.286691,-1.128485,0.031532,-0.736986,-0.154018,-0.552428,-0.305122,0
54805,-1.119163,0.095665,0.095082,0.080096,0.083952,-0.415276,-1.018775,1.198336,-0.671858,1.356878,-0.154018,1.167657,-0.305122,1
54806,-1.132622,0.072031,0.019048,0.080096,0.085013,-0.415276,-0.757681,-1.904092,-0.906322,-0.736986,-0.154018,-1.375077,-0.305122,1
54807,0.545912,0.056245,0.114188,0.080096,0.083952,-0.415276,-1.018775,-1.904092,-0.202931,-0.736986,-0.154018,-1.075931,-0.305122,1

In [29]:
# Apply onehot encoding for minimal categories
# gender
data_train = pd.get_dummies(data_train, columns=['gender'],dtype=int,drop_first=True)
data_test = pd.get_dummies(data_test, columns=['gender'],dtype=int,drop_first=True)

In [30]:
# Apply Target encoding on multiple values cloumns
#  'department', 'region', 'education', 'recruitment_channel
data_train['department']= data_train.groupby('department')['is_promoted'].transform("mean")
data_train['region']= data_train.groupby('region')['is_promoted'].transform("mean")
data_train['education']= data_train.groupby('education')['is_promoted'].transform("mean")
data_train['recruitment_channel']= data_train.groupby('recruitment_channel')['is_promoted'].transform("mean")

In [31]:
data_train

,employee_id,department,region,education,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted,gender_m
0,65438,0.072031,0.106546,0.098559,0.085013,1,35,5.0,8,1,0,49,0,0
1,65141,0.090148,0.114188,0.080096,0.083952,1,30,5.0,4,0,0,60,0,1
2,7513,0.072031,0.060641,0.080096,0.085013,1,34,3.0,7,0,0,50,0,1
3,2542,0.072031,0.116596,0.080096,0.083952,2,39,1.0,10,0,0,50,0,1
4,48945,0.107593,0.063274,0.080096,0.083952,1,45,3.0,2,0,0,73,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54803,3030,0.107593,0.074970,0.080096,0.085013,1,48,3.0,17,0,0,78,0,1
54804,74592,0.090148,0.078963,0.098559,0.083952,1,37,2.0,6,0,0,56,0,0
54805,13918,0.095665,0.095082,0.080096,0.083952,1,27,5.0,3,1,0,79,0,1
54806,13614,0.072031,0.019048,0.080096,0.085013,1,29,1.0,2,0,0,45,0,1
54807,51526,0.056245,0.114188,0.080096,0.083952,1,27,1.0,5,0,0,49,0,1

In [65]:
#Apply Standard Scaler on Numerical train Data
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
#Apply Standard scaling to transform data
scaler = StandardScaler()

data_train[num_col_test] = scaler.fit_transform(data_train[num_col_test])

In [58]:
#APPLY Standard Scaler on Numerical test Data
data_test[num_col_test] = scaler.fit_transform(data_test[num_col_test])

In [90]:
# Define features columns of trained data
data_train_array = pd.DataFrame(data_train,columns=data_train.columns)
X_tn = data_train_array.drop("is_promoted", axis=1)
X_tn = X_tn.drop("employee_id", axis=1)
# Define target column
y_tn = data_train_array["is_promoted"]

In [91]:
# Define features columns of test data
data_test_array = pd.DataFrame(data_test,columns=data_test.columns)
X_tt = data_test_array

In [92]:
from sklearn.linear_model import LinearRegression #first model supervised regression model

model = LinearRegression()  # model named as model
model.fit(X_tn, y_tn) # teaching the trained values - machine learning happend

LinearRegression()

In [93]:
y_pred = model.predict(X_tn)
y_pred # predicted answers

array([ 0.27527611, -0.13500994, -0.35748846, ...,  0.49670945,
       -0.6949732 , -0.17772189])

In [94]:
results = pd.DataFrame({
    "Actual (₹)": y_tn.values,
    "Predicted (₹)": y_pred.astype(int),
    "diff": (y_tn.values - y_pred).astype(int)

})
results

       Actual (₹)  Predicted (₹)  diff
0       -0.305122              0     0
1       -0.305122              0     0
2       -0.305122              0     0
3       -0.305122              0     0
4       -0.305122              0     0
...           ...            ...   ...
54803   -0.305122              0     0
54804   -0.305122              0     0
54805   -0.305122              0     0
54806   -0.305122              0     0
54807   -0.305122              0     0

[54808 rows x 3 columns]

In [95]:
from sklearn.metrics import r2_score, mean_absolute_error # regression score and mean absolute error
# Regression metrics 99.63% accuracy
r2 = r2_score(y_tn, y_pred)
mae = mean_absolute_error(y_tn, y_pred)

print(f"\nR² Score: {r2:.4f}")
print(f"Mean Absolute Error: ₹{int(mae):,}")

R² Score: 0.1260
Mean Absolute Error: ₹0

In [96]:
X_tn.train = model.predict
X_tn.test = model.predict(X_tn)
y_tn.train = model.predict(X_tn)
y_tn.test = model.predict(X_tn)

/tmp/ipykernel_707/125735590.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  X_tn.test = model.predict(X_tn)

In [97]:
from sklearn.model_selection import train_test_split
X_train, Xtest, y_train, ytest = train_test_split(X_tn,y_tn,random_state=42) # 75% 25%

In [102]:
X_train.shape # X_test.shape = (3, 11)

,department,region,education,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,gender_m
9861,0.072031,0.019048,0.080096,0.083952,-0.415276,-1.279868,1.198336,-1.140785,-0.736986,6.492758,-1.001145,1
14074,0.090148,0.056848,0.080096,0.083952,1.226063,0.025598,-1.904092,0.734923,-0.736986,-0.154018,-0.627214,0
44406,0.107593,0.114188,0.098559,0.085013,-0.415276,0.547785,0.422729,0.734923,-0.736986,-0.154018,1.242443,0
2990,0.056245,0.063274,0.080096,0.083952,-0.415276,-1.149321,-0.352878,-0.671858,-0.736986,-0.154018,-1.225504,0
10263,0.090148,0.080916,0.080096,0.083952,-0.415276,-1.279868,1.198336,-1.140785,1.356878,-0.154018,-0.103710,0
...,...,...,...,...,...,...,...,...,...,...,...,...
44732,0.096386,0.114188,0.098559,0.085013,2.867403,0.156145,-0.352878,-0.437395,-0.736986,-0.154018,0.270221,0
54343,0.096386,0.080126,0.080096,0.085013,-0.415276,-1.018775,1.198336,-1.140785,-0.736986,-0.154018,0.345008,0
38158,0.090148,0.056274,0.080096,0.085013,-0.415276,-0.104948,1.198336,0.265996,1.356878,-0.154018,0.120649,0
860,0.095665,0.079060,0.098559,0.083952,2.867403,0.025598,1.198336,-0.671858,-0.736986,-0.154018,1.691161,1
15795,0.056245,0.114188,0.080096,0.085013,-0.415276,-0.627135,-1.904092,-0.906322,-0.736986,-0.154018,-0.776786,1

In [99]:
y_train.shape

(41106,)

In [100]:
dept_mean = data_train.groupby("department")["is_promoted"].mean()
region_mean = data_train.groupby("region")["is_promoted"].mean()
education_mean = data_train.groupby("education")["is_promoted"].mean()
recruitment_mean = data_train.groupby("recruitment_channel")["is_promoted"].mean()
no_of_trainings_mean = data_train.groupby("no_of_trainings")["is_promoted"].mean()
age_mean = data_train.groupby("age")["is_promoted"].mean
previous_year_rating_mean = data_train.groupby("previous_year_rating")["is_promoted"].mean()
length_of_service_mean = data_train.groupby("length_of_service")["is_promoted"].mean()
KPIs_met_mean = data_train.groupby("KPIs_met >80%")["is_promoted"].mean
awards_won_mean = data_train.groupby("awards_won?")["is_promoted"].mean
avg_training_score_mean = data_train.groupby("avg_training_score")["is_promoted"].mean
gender_mean = data_train.groupby("gender_m")["is_promoted"].mean

In [108]:
num_col_test

Index(['employee_id', 'no_of_trainings', 'age', 'previous_year_rating',
       'length_of_service', 'KPIs_met >80%', 'awards_won?',
       'avg_training_score'],
      dtype='object')

In [123]:
# department,	region,	education,	recruitment_channel,	no_of_trainings,	age	previous_year_rating
# length_of_service,	KPIs_met >80%,	awards_won?,	avg_training_score,	gender_m
# target column - is_promoted
is_promoted = pd.DataFrame({
    "department": [0.072031], #dept_mean["Finance"]
    "region": [0.019048], #region_mean["region_6"]
    "education": [0.080096], #education_mean["Bachelor's"]
    "recruitment_channel": [0.083952], #recruitment_mean["other"]
    "no_of_trainings": [1.226063], #no_of_trainings_mean["3"]
    "age": [0.547785	], #age_mean["3.0"]
    "previous_year_rating": [1.198336	], #previous_year_rating_mean["3.0"]
    "length_of_service": [0.734923], #length_of_service_mean["5"]
    "KPIs_met >80%": [1.356878], #KPIs_met_mean["1"]
    "awards_won?": [6.492758], #awards_won_mean["0"]
    "avg_training_score": [1.242443	], #avg_training_score_mean["77"]
    "gender_m": [0] #gender_mean["m"]
})

promoted = model.predict(is_promoted)
print(f"Promoted: ₹{int(promoted[0]):,}")

Promoted: ₹1