In [1]:
# Supervisory Learning - Logistic Regression
import seaborn as sns
import pandas as pd
import statistics as st
import matplotlib.pyplot as plt

# Read the training data from the uploaded file
data_train=pd.read_csv('/content/train_LZdllcl.csv')
data_train

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,65438,Sales & Marketing,region_7,Master's & above,f,sourcing,1,35,5.0,8,1,0,49,0
1,65141,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,0,60,0
2,7513,Sales & Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,0,50,0
3,2542,Sales & Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,0,50,0
4,48945,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,0,73,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54803,3030,Technology,region_14,Bachelor's,m,sourcing,1,48,3.0,17,0,0,78,0
54804,74592,Operations,region_27,Master's & above,f,other,1,37,2.0,6,0,0,56,0
54805,13918,Analytics,region_1,Bachelor's,m,other,1,27,5.0,3,1,0,79,0
54806,13614,Sales & Marketing,region_9,NaN,m,sourcing,1,29,1.0,2,0,0,45,0
54807,51526,HR,region_22,Bachelor's,m,other,1,27,1.0,5,0,0,49,0

In [16]:
# Read the test data from the uploaded file
data_test=pd.read_csv('/content/test_2umaH9m.csv')
data_test

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score
0,8724,Technology,region_26,Bachelor's,m,sourcing,1,24,NaN,1,1,0,77
1,74430,HR,region_4,Bachelor's,f,other,1,31,3.0,5,0,0,51
2,72255,Sales & Marketing,region_13,Bachelor's,m,other,1,31,1.0,4,0,0,47
3,38562,Procurement,region_2,Bachelor's,f,other,3,31,2.0,9,0,0,65
4,64486,Finance,region_29,Bachelor's,m,sourcing,1,30,4.0,7,0,0,61
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23485,53478,Legal,region_2,Below Secondary,m,sourcing,1,24,3.0,1,0,0,61
23486,25600,Technology,region_25,Bachelor's,m,sourcing,1,31,3.0,7,0,0,74
23487,45409,HR,region_16,Bachelor's,f,sourcing,1,26,4.0,4,0,0,50
23488,1186,Procurement,region_31,Bachelor's,m,sourcing,3,27,NaN,1,0,0,70
23489,5973,Technology,region_17,Master's & above,m,other,3,40,5.0,5,1,0,89

In [3]:
#checking the data duplicates in train data
data_train.duplicated().sum()

np.int64(0)

In [4]:
#checking the data duplicates in test data
data_test.duplicated().sum()

np.int64(0)

In [5]:
# check null values in train data
data_train.isnull().sum()

employee_id                0
department                 0
region                     0
education               2409
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
is_promoted                0
dtype: int64

In [8]:
# Replace the education column null values by mode
data_train.loc[data_train["education"].isna(),"education"] = st.mode(data_train["education"])
data_train.isnull().sum()

employee_id                0
department                 0
region                     0
education                  0
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
is_promoted                0
dtype: int64

In [12]:
# Replace the previous_year_rating column null values by first value
data_train.loc[data_train["previous_year_rating"].isna(),"previous_year_rating"] = data_train["previous_year_rating"][0]
data_train.isnull().sum()

employee_id             0
department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
is_promoted             0
dtype: int64

In [18]:
# Replace the education column null values by mode
data_test.loc[data_test["education"].isna(),"education"] = st.mode(data_test["education"])
data_test.isnull().sum()

employee_id             0
department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
dtype: int64

In [19]:
# Replace the previous_year_rating column null values by first value
data_test.loc[data_test["previous_year_rating"].isna(),"previous_year_rating"] = data_test["previous_year_rating"][1]
data_test.isnull().sum()

employee_id             0
department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
dtype: int64

In [20]:
#Define numerical columns and text columns in the train data
from sklearn.impute import SimpleImputer
num_col_train = data_train.select_dtypes(include=['number']).columns
cat_col_train = data_train.select_dtypes(exclude=["number"]).columns

In [21]:
cat_col_train

Index(['department', 'region', 'education', 'gender', 'recruitment_channel'], dtype='object')

In [22]:
#Define numerical columns and text columns in the test data
from sklearn.impute import SimpleImputer
num_col_test = data_test.select_dtypes(include=['number']).columns
cat_col_test = data_test.select_dtypes(exclude=["number"]).columns

In [23]:
cat_col_test

Index(['department', 'region', 'education', 'gender', 'recruitment_channel'], dtype='object')

In [32]:
num_col_train

Index(['employee_id', 'no_of_trainings', 'age', 'previous_year_rating',
       'length_of_service', 'KPIs_met >80%', 'awards_won?',
       'avg_training_score', 'is_promoted'],
      dtype='object')

In [33]:
num_col_test

Index(['employee_id', 'no_of_trainings', 'age', 'previous_year_rating',
       'length_of_service', 'KPIs_met >80%', 'awards_won?',
       'avg_training_score'],
      dtype='object')

In [28]:
#data_train['department'].value_counts()
#data_train['region'].value_counts()
#data_train['education'].value_counts()
#data_train['gender'].value_counts()
data_train['recruitment_channel'].value_counts()

recruitment_channel
other       30446
sourcing    23220
referred     1142
Name: count, dtype: int64

In [29]:
# Apply onehot encoding for minimal categories
# gender
data_train = pd.get_dummies(data_train, columns=['gender'],dtype=int,drop_first=True)
data_test = pd.get_dummies(data_test, columns=['gender'],dtype=int,drop_first=True)

In [30]:
# Apply Target encoding on multiple values cloumns
#  'department', 'region', 'education', 'recruitment_channel
data_train['department']= data_train.groupby('department')['is_promoted'].transform("mean")
data_train['region']= data_train.groupby('region')['is_promoted'].transform("mean")
data_train['education']= data_train.groupby('education')['is_promoted'].transform("mean")
data_train['recruitment_channel']= data_train.groupby('recruitment_channel')['is_promoted'].transform("mean")

In [31]:
data_train

,employee_id,department,region,education,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted,gender_m
0,65438,0.072031,0.106546,0.098559,0.085013,1,35,5.0,8,1,0,49,0,0
1,65141,0.090148,0.114188,0.080096,0.083952,1,30,5.0,4,0,0,60,0,1
2,7513,0.072031,0.060641,0.080096,0.085013,1,34,3.0,7,0,0,50,0,1
3,2542,0.072031,0.116596,0.080096,0.083952,2,39,1.0,10,0,0,50,0,1
4,48945,0.107593,0.063274,0.080096,0.083952,1,45,3.0,2,0,0,73,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54803,3030,0.107593,0.074970,0.080096,0.085013,1,48,3.0,17,0,0,78,0,1
54804,74592,0.090148,0.078963,0.098559,0.083952,1,37,2.0,6,0,0,56,0,0
54805,13918,0.095665,0.095082,0.080096,0.083952,1,27,5.0,3,1,0,79,0,1
54806,13614,0.072031,0.019048,0.080096,0.085013,1,29,1.0,2,0,0,45,0,1
54807,51526,0.056245,0.114188,0.080096,0.083952,1,27,1.0,5,0,0,49,0,1

In [34]:
#Apply Standard Scaler on Numerical train Data
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
#Apply Standard scaling to transform data
scaler = StandardScaler()

data_train[num_col_train] = scaler.fit_transform(data_train[num_col_train])

In [35]:
#APPLY Standard Scaler on Numerical test Data
data_test[num_col_test] = scaler.fit_transform(data_test[num_col_test])

In [47]:
# Define features columns of trained data
data_train_array = pd.DataFrame(data_train,columns=data_train.columns)
X_tn = data_train_array.drop("is_promoted", axis=1)
# Define target column
y_tn = data_train_array["is_promoted"]

In [48]:
# Define features columns of test data
data_test_array = pd.DataFrame(data_test,columns=data_test.columns)
X_tt = data_test_array
X_tt

,employee_id,department,region,education,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,gender_m
0,-1.339088,Technology,region_26,Bachelor's,sourcing,-0.423094,-1.404150,-0.257191,-1.143200,1.336715,-0.152665,1.024263,1
1,1.563078,HR,region_4,Bachelor's,other,-0.423094,-0.492612,-0.257191,-0.192590,-0.748103,-0.152665,-0.914377,0
2,1.467011,Sales & Marketing,region_13,Bachelor's,other,-0.423094,-0.492612,-1.900667,-0.430243,-0.748103,-0.152665,-1.212629,1
3,-0.021175,Procurement,region_2,Bachelor's,other,2.905264,-0.492612,-1.078929,0.758019,-0.748103,-0.152665,0.129506,0
4,1.123862,Finance,region_29,Bachelor's,sourcing,-0.423094,-0.622832,0.564547,0.282714,-0.748103,-0.152665,-0.168746,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23485,0.637650,Legal,region_2,Below Secondary,sourcing,-0.423094,-1.404150,-0.257191,-1.143200,-0.748103,-0.152665,-0.168746,1
23486,-0.593693,Technology,region_25,Bachelor's,sourcing,-0.423094,-0.492612,-0.257191,0.282714,-0.748103,-0.152665,0.800574,1
23487,0.281250,HR,region_16,Bachelor's,sourcing,-0.423094,-1.143711,0.564547,-0.430243,-0.748103,-0.152665,-0.988940,0
23488,-1.672034,Procurement,region_31,Bachelor's,sourcing,2.905264,-1.013491,-0.257191,-1.143200,-0.748103,-0.152665,0.502321,1
23489,-1.460597,Technology,region_17,Master's & above,other,2.905264,0.679366,1.386285,-0.192590,1.336715,-0.152665,1.919020,1

In [54]:
# Logistic Regression with Best parameters
#log_reg = LogisticRegression(C=10, penalty='l2', solver='lbfgs') # best parameters can be take from below result use the best parameters here C=10, penalty='l2', solver= 'lbfgs'

# Logistic Regression with default parameters
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_tn, y_tn, test_size=0.2, random_state=42, stratify=y_tn ) #remove bias
log_reg = LogisticRegression()

log_reg.fit(X_train, y_train)
# Train & Test Accuracy
train_acc_logreg = accuracy_score(y_train, log_reg.predict(X_train))
test_acc_logreg = accuracy_score(y_test, log_reg.predict(X_test))

print("Logistic Regression (Default)")
print("Train Accuracy:", train_acc_logreg)
print("Test Accuracy:", test_acc_logreg)

In [ ]:
# MODEL BUILDING USING LOGESTIC REGRESSSION
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

param_grid = {
    "C": [0.01, 0.1, 1],          # if smaller then simpler models, Larger values more complex, can overfit
    "solver": ["lbfgs", "liblinear"], # weight optimization lbfgs for large data, other for small data
    "penalty": ["l2","elastic","l1"]  # avoid over fitting
}
# 3 x 2 x 3 = 18 combinations possible

# GridSearchCV to check all the combinations
grid = GridSearchCV(LogisticRegression(max_iter=100), param_grid, cv=5, scoring="accuracy", n_jobs=-1)
grid.fit(X_train, y_train)

best_log_reg = grid.best_estimator_

# Train & Test Accuracy after tuning
train_acc_tuned_logreg = accuracy_score(y_train, best_log_reg.predict(X_train))
test_acc_tuned_logreg = accuracy_score(y_test, best_log_reg.predict(X_test))

# PRINT OUTPUT
print("\nLogistic Regression (Tuned)")
print("Best Params:", grid.best_params_)
print("Train Accuracy:", train_acc_tuned_logreg)
print("Test Accuracy:", test_acc_tuned_logreg)

In [ ]:
# MODEL BUILDING USING KNN
from sklearn.neighbors import KNeighborsClassifier

knn_default = KNeighborsClassifier()
knn_default.fit(X_train, y_train)

train_acc_knn = accuracy_score(y_train, knn_default.predict(X_train))
test_acc_knn = accuracy_score(y_test, knn_default.predict(X_test))

# PRINT OUTPUT
print("KNN (Default)")
print("Train Accuracy:", train_acc_knn)
print("Test Accuracy:", test_acc_knn)