In [69]:
import seaborn as sns
import pandas as pd
import statistics as st
import matplotlib.pyplot as plt
# Read the data from uploaded file car details v4.csv
data=pd.read_csv('/content/bank-additional-full.csv')
data

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

In [70]:
#checking the data duplicates
data.duplicated().sum()

np.int64(12)

In [71]:
data.drop_duplicates(inplace=True) #remove duplicates

In [72]:
#checking the data duplicates
data.duplicated().sum()

np.int64(0)

In [73]:
# check null value
data.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [74]:
from sklearn.impute import SimpleImputer
#Define numerical columns and text columns
num_col = data.select_dtypes(include=['number']).columns
cat_col = data.select_dtypes(exclude=["number"]).columns

In [75]:
cat_col

Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'day_of_week', 'poutcome', 'y'],
      dtype='object')

In [18]:
data['job'].value_counts()

job
admin.           10419
blue-collar       9253
technician        6739
services          3967
management        2924
retired           1718
entrepreneur      1456
self-employed     1421
housemaid         1060
unemployed        1014
student            875
unknown            330
Name: count, dtype: int64

In [76]:
# Apply onehot encoding for minimal categories
# marital, default, housing,	loan, contact
data = pd.get_dummies(data, columns=['marital'],dtype=int,drop_first=True)
data = pd.get_dummies(data, columns=['default'],dtype=int,drop_first=True)
data = pd.get_dummies(data, columns=['housing'],dtype=int,drop_first=True)
data = pd.get_dummies(data, columns=['loan'],dtype=int,drop_first=True)
data = pd.get_dummies(data, columns=['contact'],dtype=int,drop_first=True)

In [77]:
data

,age,job,education,month,day_of_week,duration,campaign,pdays,previous,poutcome,...,marital_married,marital_single,marital_unknown,default_unknown,default_yes,housing_unknown,housing_yes,loan_unknown,loan_yes,contact_telephone
0,56,housemaid,basic.4y,may,mon,261,1,999,0,nonexistent,...,1,0,0,0,0,0,0,0,0,1
1,57,services,high.school,may,mon,149,1,999,0,nonexistent,...,1,0,0,1,0,0,0,0,0,1
2,37,services,high.school,may,mon,226,1,999,0,nonexistent,...,1,0,0,0,0,0,1,0,0,1
3,40,admin.,basic.6y,may,mon,151,1,999,0,nonexistent,...,1,0,0,0,0,0,0,0,0,1
4,56,services,high.school,may,mon,307,1,999,0,nonexistent,...,1,0,0,0,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,professional.course,nov,fri,334,1,999,0,nonexistent,...,1,0,0,0,0,0,1,0,0,0
41184,46,blue-collar,professional.course,nov,fri,383,1,999,0,nonexistent,...,1,0,0,0,0,0,0,0,0,0
41185,56,retired,university.degree,nov,fri,189,2,999,0,nonexistent,...,1,0,0,0,0,0,1,0,0,0
41186,44,technician,professional.course,nov,fri,442,1,999,0,nonexistent,...,1,0,0,0,0,0,0,0,0,0
41187,74,retired,professional.course,nov,fri,239,3,999,1,failure,...,1,0,0,0,0,0,1,0,0,0

In [78]:
# Apply Target encoding since there multiple values in the below feature cloumns
#  job, education, month, day_of_week,	poutcome
data['job']= data.groupby('job')['nr.employed'].transform("mean")

data['education'] = data.groupby('education')['nr.employed'].transform("mean")

data['month'] = data.groupby('month')['nr.employed'].transform("mean")

data['day_of_week'] = data.groupby('day_of_week')['nr.employed'].transform("mean")

data['poutcome'] = data.groupby('poutcome')['nr.employed'].transform("mean")

In [79]:
data['y'] = data['y'].replace({'yes': 1, 'no': 0})

/tmp/ipython-input-895795217.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['y'] = data['y'].replace({'yes': 1, 'no': 0})

In [80]:
data

,age,job,education,month,day_of_week,duration,campaign,pdays,previous,poutcome,...,marital_married,marital_single,marital_unknown,default_unknown,default_yes,housing_unknown,housing_yes,loan_unknown,loan_yes,contact_telephone
0,56,5179.529623,5170.124880,5149.522242,5164.553466,261,1,999,0,5181.207069,...,1,0,0,0,0,0,0,0,0,1
1,57,5171.604159,5164.988394,5149.522242,5164.553466,149,1,999,0,5181.207069,...,1,0,0,1,0,0,0,0,0,1
2,37,5171.604159,5164.988394,5149.522242,5164.553466,226,1,999,0,5181.207069,...,1,0,0,0,0,0,1,0,0,1
3,40,5164.136990,5174.710956,5149.522242,5164.553466,151,1,999,0,5181.207069,...,1,0,0,0,0,0,0,0,0,1
4,56,5171.604159,5164.988394,5149.522242,5164.553466,307,1,999,0,5181.207069,...,1,0,0,0,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,5122.261525,5170.122805,5173.025683,5165.118234,334,1,999,0,5181.207069,...,1,0,0,0,0,0,1,0,0,0
41184,46,5175.613488,5170.122805,5173.025683,5165.118234,383,1,999,0,5181.207069,...,1,0,0,0,0,0,0,0,0,0
41185,56,5122.261525,5163.248027,5173.025683,5165.118234,189,2,999,0,5181.207069,...,1,0,0,0,0,0,1,0,0,0
41186,44,5175.617258,5170.122805,5173.025683,5165.118234,442,1,999,0,5181.207069,...,1,0,0,0,0,0,0,0,0,0
41187,74,5122.261525,5170.122805,5173.025683,5165.118234,239,3,999,1,5092.589534,...,1,0,0,0,0,0,1,0,0,0

In [81]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
#Apply Standard scaling to transform data
scaler = StandardScaler()

data[num_col] = scaler.fit_transform(data[num_col])

In [82]:
# Define features columns
data_array = pd.DataFrame(data,columns=data.columns)
X = data_array.drop("y", axis=1)
# Define target column
y = data_array["y"]

#X_train, X_test, y_train, y_test = train_test_split(
 #   X, y, test_size=0.25, random_state=42)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y #remove bias
)

In [83]:
y

0        0
1        0
2        0
3        0
4        0
        ..
41183    1
41184    0
41185    0
41186    1
41187    0
Name: y, Length: 41176, dtype: int64

In [84]:
# Logistic Regression with default parameters
log_reg = LogisticRegression()
# Logistic Regression with best parameters
#log_reg = LogisticRegression(C=10, penalty='l2', solver='lbfgs') # best parameters can be take from below result use the best parameters here C=10, penalty='l2', solver= 'lbfgs'
log_reg.fit(X_train, y_train)
# Train & Test Accuracy
train_acc_logreg = accuracy_score(y_train, log_reg.predict(X_train))
test_acc_logreg = accuracy_score(y_test, log_reg.predict(X_test))

print("Logistic Regression (Default)")
print("Train Accuracy:", train_acc_logreg)
print("Test Accuracy:", test_acc_logreg)

Logistic Regression (Default)
Train Accuracy: 0.8988767455980571
Test Accuracy: 0.9014084507042254

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [86]:
# MODEL BUILDING USING LOGESTIC REGRESSSION
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

param_grid = {
    "C": [0.01, 0.1, 1],          # if smaller then simpler models, Larger values more complex, can overfit
    "solver": ["lbfgs", "liblinear"], # weight optimization lbfgs for large data, other for small data
    "penalty": ["l2","elastic","l1"]  # avoid over fitting
}
# 3 x 2 x 3 = 18 combinations possible

# GridSearchCV to check all the combinations
grid = GridSearchCV(LogisticRegression(max_iter=100), param_grid, cv=5, scoring="accuracy", n_jobs=-1)
grid.fit(X_train, y_train)

best_log_reg = grid.best_estimator_

# Train & Test Accuracy after tuning
train_acc_tuned_logreg = accuracy_score(y_train, best_log_reg.predict(X_train))
test_acc_tuned_logreg = accuracy_score(y_test, best_log_reg.predict(X_test))

# PRINT OUTPUT
print("\nLogistic Regression (Tuned)")
print("Best Params:", grid.best_params_)
print("Train Accuracy:", train_acc_tuned_logreg)
print("Test Accuracy:", test_acc_tuned_logreg)

KeyboardInterrupt:

In [87]:
# MODEL BUILDING USING KNN
from sklearn.neighbors import KNeighborsClassifier

knn_default = KNeighborsClassifier()
knn_default.fit(X_train, y_train)

train_acc_knn = accuracy_score(y_train, knn_default.predict(X_train))
test_acc_knn = accuracy_score(y_test, knn_default.predict(X_test))

# PRINT OUTPUT
print("KNN (Default)")
print("Train Accuracy:", train_acc_knn)
print("Test Accuracy:", test_acc_knn)

KNN (Default)
Train Accuracy: 0.9242258652094718
Test Accuracy: 0.9011656143759106

In [88]:
# MODEL BUILDING USING SVM
from sklearn.svm import SVC

# Default SVC (kernel='rbf', C=1.0, gamma='scale')
svc = SVC()
svc.fit(X_train, y_train)

# Train & Test accuracy
train_acc_svc = svc.score(X_train, y_train)
test_acc_svc= svc.score(X_test, y_test)

#PRINT OUTPUT
print("SVC (Default)")
print("Train Accuracy:", train_acc_svc)
print("Test Accuracy:", test_acc_svc)

SVC (Default)
Train Accuracy: 0.8873406193078324
Test Accuracy: 0.8873239436619719

In [89]:
# MODEL BUILDING USING DECISION TREE CLASSIFIER
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier


bagging = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=100,   #sv1, sv2......sv100
    random_state=42
)

bagging.fit(X_train, y_train)
y_pred = bagging.predict(X_test)

print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred))

Decision Tree Accuracy: 0.9100291403593977

In [90]:
# ENSEMBLE MODELS - RANDOM FOREST
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred))

Random Forest Accuracy: 0.9130645944633318

In [91]:
# ENSEMBLE MODELS - BAGGING CLASSIFIER
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

bagging = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=100,   #sv1, sv2......sv100
    random_state=42
)

bagging.fit(X_train, y_train)
y_pred = bagging.predict(X_test)

print("Bagging Accuracy:", accuracy_score(y_test, y_pred))

Bagging Accuracy: 0.9100291403593977

In [92]:
# ENSEMBLE MODELS - ADA BOOSTING MODEL
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score
ada = AdaBoostClassifier(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

ada.fit(X_train, y_train)
y_pred = ada.predict(X_test)

print("AdaBoost Accuracy:", accuracy_score(y_test, y_pred))

AdaBoost Accuracy: 0.8949732880038854